version: '3.8'
services:
  keycloak:
    build: .
    container_name: keycloak20
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: 57.129.44.18
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    entrypoint: ["/opt/keycloak/bin/entrypoint.sh"]
    command: ["start-dev"]

    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data:
