version: '3.8'

services:
  fineract:
    image: 57.129.44.18:5001/fineract
    ports:
      - "8443:8443"
#      - "5000:5000"
    env_file:
      - ./config/docker/env/fineract.env
      - ./config/docker/env/fineract-common.env
      - ./config/docker/env/fineract-mariadb.env
    depends_on:
      db:
        condition: service_healthy


  db:
    extends:
      file: ./config/docker/compose/mariadb.yml
      service: mariadb

  mifos:
    image: 57.129.44.18:5001/mifos
    ports:
      - "9090:80"

